kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: redis
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        deploy: redis
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
              readOnly: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-data
