name: Bloom User Service CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main, feature/testing ]
jobs:
  user-service:
    name: user-service-ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        run: make tag=${GITHUB_SHA::8} push_bloom_user_service