name: Bloom User Service CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main, feature/testing ]
jobs:
  user-service:
    name: user-service-ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: make tag=${GITHUB_SHA::8} push_bloom_user_service

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.CLUSTER_SA }}
          project_id: helpful-ally-314019
          export_default_credentials: true

      - name: get-cred
        run: gcloud container clusters get-credentials bloom-cluster --region europe-west3-a --project  helpful-ally-314019

      - name: Helm install
        run: make tag=${GITHUB_SHA::8} deploy_bloom_user_service