name: Bloom User Service CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main, feature/testing ]
    paths:
      - 'users-service/**'
jobs:
  user-service:
    name: user-service-ci
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        run: docker build . -t bloom_user_service:v1.0.0
      - name: Docker Tag
        run: docker tag  bloom_user_service:v1.0.0 singaravelan21/bloom_user_service:v1.0.0
      - name: Docker Push
        run: docker push singaravelan21/bloom_user_service:v1.0.0